name: Deploy to Staging
on:
  push:
    branches:
      - staging

jobs:
  # docker-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: serlo/configure-repositories/actions/setup-node@main
  #     - uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: '${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}'
  #     - run: gcloud auth configure-docker
  #     - uses: google-github-actions/setup-gcloud@v2
  #     - run: yarn deploy:images:staging
  deploy-image:
    runs-on: ubuntu-latest
    # needs: docker-image
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_STAGING_SERVICE_ACCOUNT }}'
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: serlo-staging-cluster
          location: europe-west3-a
      - run: kubectl delete pod -n api -l app=server
      - run: kubectl delete pod -n api -l app=swr-queue-worker
